### ISSUE TITLE
Search not wkrking

### ISSUE THREAD

**Issue by Clopy9** [dwdyer/watchmaker#37]
After the most recent update, searching opens a separate search window in the app. However, neither window completes a search. It cycles back to the home screen. 

Unable to search designs currently. Running on iPhone XR, app version 8.0.6

**Comment by dwdyer** [comment]
I think you've got the wrong project. I've no idea what you're referring to. This is a Java library, it hasn't been updated for ages, it has no search function, and it doesn't run on iPhones.
